(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],D={easy:{n:6,label:'Easy',base:3500},classic:{n:8,label:'Classic',base:6000},hard:{n:10,label:'Hard',base:9000}},KEY='stardoku-v3';
let profile=load(),selected=profile.selected||'classic',g=null,timer=null,pending=new Map(),toastTimer;
function defaults(){return{levels:{easy:1,classic:1,hard:1},solved:0,total:0,streak:0,best:0,selected:'classic'}}
function load(){try{return Object.assign(defaults(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return defaults()}}
function save(){localStorage.setItem(KEY,JSON.stringify(profile))}
function rng(seed){let x=seed>>>0;return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function hash(s){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function shuffle(a,r){for(let i=a.length-1;i;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function permutation(n,r){const out=[],used=Array(n).fill(0);function go(row){if(row===n)return true;for(const c of shuffle([...Array(n).keys()],r)){if(used[c]||(row&&Math.abs(c-out[row-1])<2))continue;used[c]=1;out.push(c);if(go(row+1))return true;out.pop();used[c]=0}return false}return go(0)?out:null}
function grow(n,sol,r){const a=Array(n*n).fill(-1),front=[];for(let k=0;k<n;k++){const i=k*n+sol[k];a[i]=k}function add(i){const y=Math.floor(i/n),x=i%n;for(const [dy,dx] of [[1,0],[-1,0],[0,1],[0,-1]]){const yy=y+dy,xx=x+dx;if(yy>=0&&yy<n&&xx>=0&&xx<n&&a[yy*n+xx]<0)front.push(yy*n+xx)}}for(let k=0;k<n;k++)add(k*n+sol[k]);let left=n*n-n;while(left){let i=front.splice(Math.floor(r()*front.length),1)[0];if(i==null)return null;if(a[i]>=0)continue;const y=Math.floor(i/n),x=i%n,near=[];for(const [dy,dx] of [[1,0],[-1,0],[0,1],[0,-1]]){const yy=y+dy,xx=x+dx;if(yy>=0&&yy<n&&xx>=0&&xx<n&&a[yy*n+xx]>=0)near.push(a[yy*n+xx])}if(!near.length)continue;a[i]=near[Math.floor(r()*near.length)];left--;add(i)}return a}
function countSolutions(reg,n,limit=2){let count=0,usedC=0,usedR=0;function go(row,prev){if(count>=limit)return;if(row===n){count++;return}for(let c=0;c<n;c++){const cb=1<<c,rb=1<<reg[row*n+c];if((usedC&cb)||(usedR&rb)||(row&&Math.abs(c-prev)<2))continue;usedC|=cb;usedR|=rb;go(row+1,c);usedC^=cb;usedR^=rb}}go(0,-9);return count}
function make(d,level){const n=D[d].n,r=rng(hash(`${d}:${level}:jackmhny`));for(let tries=0;tries<240;tries++){const sol=permutation(n,r);if(!sol)continue;const reg=grow(n,sol,r);if(reg&&countSolutions(reg,n)===1){const order=shuffle([...Array(n).keys()],r);return{n,sol,reg,order}}}throw Error('generation failed')}
function mini(){const p=[1,1,3,3,5,1,1,3,5,5,7,7,3,5,5,7,2,2,2,4,7,2,4,4,4],stars=new Set([2,5,13,16,24]);$('#mini').innerHTML=p.map((v,i)=>`<span class="p${v}">${stars.has(i)?'★':'×'}</span>`).join('')}
function renderIntro(){$$('.mode').forEach(b=>b.setAttribute('aria-pressed',b.dataset.d===selected));for(const d in D)$(`[data-level="${d}"]`).textContent=`Level ${profile.levels[d]}`;$('#start').textContent=`Start level ${profile.levels[selected]}`;$('#solved').textContent=profile.solved;$('#total').textContent=profile.total.toLocaleString();$('#best').textContent=profile.best;$('#intro').hidden=false;$('#gameview').hidden=true;stopTimer()}
function start(d=selected,level=profile.levels[d]){clearPending();const p=make(d,level);g={d,level,p,cells:Array(p.n*p.n).fill(0),strikes:3,hints:2,moves:0,start:performance.now(),done:false};renderBoard();$('#intro').hidden=true;$('#gameview').hidden=false;window.scrollTo(0,0);startTimer()}
function renderBoard(){const {n,reg,order}=g.p,b=$('#board');b.style.setProperty('--n',n);b.innerHTML='';for(let r=0;r<n;r++)for(let c=0;c<n;c++){const i=r*n+c,region=reg[i],e=document.createElement('button');e.className=`cell p${order[region]}`;e.dataset.i=i;e.dataset.state='blank';if(!r||reg[i-n]!==region)e.classList.add('bt');if(!c||reg[i-1]!==region)e.classList.add('bl');if(c===n-1)e.classList.add('lastc');if(r===n-1)e.classList.add('lastr');e.innerHTML='<span class="x">×</span><span class="star">★</span>';e.addEventListener('pointerup',tap);e.addEventListener('contextmenu',x=>x.preventDefault());e.addEventListener('dblclick',x=>x.preventDefault());b.appendChild(e)}$('#diff').textContent=`${D[g.d].label} / ${n}×${n}`;$('#level').textContent=String(g.level).padStart(3,'0');setMsg('Single tap × · double tap ★');ui()}
function tap(e){if(!g||g.done)return;e.preventDefault();const i=+e.currentTarget.dataset.i,now=performance.now(),old=pending.get(i);if(old&&now-old.t<330){clearTimeout(old.id);pending.delete(i);star(i);return}const id=setTimeout(()=>{pending.delete(i);mark(i)},275);pending.set(i,{t:now,id})}
function clearPending(){for(const v of pending.values())clearTimeout(v.id);pending.clear()}
function mark(i){if(!g||g.done)return;g.cells[i]=g.cells[i]===1?0:1;g.moves++;cell(i);ui()}
function star(i,fromHint=false){if(!g||g.done)return;const n=g.p.n,row=Math.floor(i/n),ok=g.p.sol[row]===i%n;if(g.cells[i]===2){g.cells[i]=0;g.moves++;cell(i);ui();return}if(!ok&&!fromHint){wrong(i);return}g.cells[i]=2;g.moves++;cell(i);ui();if(g.cells.filter(x=>x===2).length===n)completeLevel()}
function wrong(i){g.strikes--;g.moves++;const e=$(`.cell[data-i="${i}"]`);e.classList.add('flash');setTimeout(()=>e.classList.remove('flash'),380);ui();if(g.strikes){setMsg(`Wrong square. ${g.strikes} strike${g.strikes===1?'':'s'} left.`,'err');toast(`${g.strikes} strike${g.strikes===1?'':'s'} left`)}else{setMsg('Out of strikes. Restarting…','err');setTimeout(()=>{const d=g.d,l=g.level;start(d,l);toast('Level restarted · 3 strikes')},700)}}
function hint(){if(!g||g.done||!g.hints)return;const n=g.p.n,choices=[];for(let r=0;r<n;r++){const i=r*n+g.p.sol[r];if(g.cells[i]!==2)choices.push(i)}if(!choices.length)return;g.hints--;star(choices[Math.floor(Math.random()*choices.length)],true);setMsg('A correct star was placed.')}
function cell(i){const e=$(`.cell[data-i="${i}"]`);e.dataset.state=g.cells[i]===1?'x':g.cells[i]===2?'star':'blank'}
function elapsed(){return Math.floor((performance.now()-g.start)/1000)}
function points(){return Math.max(100,D[g.d].base-elapsed()*4-(3-g.strikes)*200-(2-g.hints)*250-g.moves*3)}
function ui(){if(!g)return;const n=g.p.n,placed=g.cells.filter(x=>x===2).length;$('#stars').textContent=`${placed} / ${n} stars`;$('#score').textContent=points().toLocaleString();$('#hint').textContent=`Hint · ${g.hints}`;$('#hint').disabled=!g.hints;$$('.strike').forEach((e,i)=>e.classList.toggle('lost',i>=g.strikes));$('#time').textContent=format(elapsed())}
function format(s){return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function completeLevel(){g.done=true;stopTimer();const p=points();profile.total+=p;profile.solved++;profile.streak++;profile.best=Math.max(profile.best,profile.streak);profile.levels[g.d]=Math.max(profile.levels[g.d],g.level+1);save();setMsg('Level complete.','ok');$('#result').textContent=`${p.toLocaleString()} points · ${format(elapsed())} · ${g.strikes} strikes left`;$('#complete').classList.add('open')}
function setMsg(t,c=''){$('#msg').textContent=t;$('#msg').className='msg'+(c?' '+c:'')}
function toast(t){clearTimeout(toastTimer);$('#toast').textContent=t;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),1400)}
function startTimer(){stopTimer();timer=setInterval(ui,1000)}function stopTimer(){clearInterval(timer);timer=null}
$$('.mode').forEach(b=>b.onclick=()=>{selected=b.dataset.d;profile.selected=selected;save();renderIntro()});$('#start').onclick=()=>start(selected,profile.levels[selected]);$('#home').onclick=renderIntro;$('#reset').onclick=()=>start(g.d,g.level);$('#hint').onclick=hint;$('#rules').onclick=()=>$('#rulesModal').classList.add('open');$('.close').onclick=()=>$('#rulesModal').classList.remove('open');$('#completeHome').onclick=()=>{$('#complete').classList.remove('open');renderIntro()};$('#next').onclick=()=>{const d=g.d;$('#complete').classList.remove('open');start(d,profile.levels[d])};
mini();renderIntro();window.__stardoku={start,make,countSolutions,get game(){return g},solve(){for(let r=0;r<g.p.n;r++)star(r*g.p.n+g.p.sol[r])}};
})();